import { act, renderHook } from '@testing-library/react';
import { afterEach, beforeEach, expect, test, vi } from 'vitest';
import { usePublishTasks } from '../usePublishTasks';
import type { CloudData } from '../client';
beforeEach(() => { vi.useFakeTimers(); Object.defineProperty(document, 'hidden', { configurable: true, value: false }); });
afterEach(() => { vi.useRealTimers(); });
test('does not poll terminal tasks, active tasks stop after completion', async () => {
  const tasks = vi.fn().mockResolvedValueOnce({ rows: [], active: true }).mockResolvedValue({ rows: [], active: false });
  const api = { tasks } as unknown as CloudData;
  const view = renderHook(() => usePublishTasks(api, 'a', 0));
  await act(async () => { await Promise.resolve(); });
  expect(tasks).toHaveBeenCalledTimes(1);
  await act(async () => { await vi.advanceTimersByTimeAsync(5000); });
  expect(tasks).toHaveBeenCalledTimes(2);
  await act(async () => { await vi.advanceTimersByTimeAsync(60000); });
  expect(tasks).toHaveBeenCalledTimes(2); view.unmount();
});
test('polling backs off failure, pauses in background and stops on unmount', async () => {
  const tasks = vi.fn().mockRejectedValueOnce(new Error('offline')).mockResolvedValue({ rows: [], active: true });
  const api = { tasks } as unknown as CloudData;
  const view = renderHook(() => usePublishTasks(api, 'a', 0));
  await act(async () => { await Promise.resolve(); });
  await act(async () => { await vi.advanceTimersByTimeAsync(5000); }); expect(tasks).toHaveBeenCalledTimes(1);
  await act(async () => { await vi.advanceTimersByTimeAsync(5000); }); expect(tasks).toHaveBeenCalledTimes(2);
  Object.defineProperty(document, 'hidden', { value: true });
  act(() => document.dispatchEvent(new Event('visibilitychange')));
  await act(async () => { await vi.advanceTimersByTimeAsync(60000); }); expect(tasks).toHaveBeenCalledTimes(2);
  Object.defineProperty(document, 'hidden', { value: false });
  await act(async () => { document.dispatchEvent(new Event('visibilitychange')); }); expect(tasks).toHaveBeenCalledTimes(3);
  view.unmount();
  await act(async () => { await vi.advanceTimersByTimeAsync(60000); }); expect(tasks).toHaveBeenCalledTimes(3);
});
